import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from datetime import datetime
import re
import time
import io
import urllib.parse

# --- ReportLab Imports for PDF ---
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER, TA_RIGHT

# ==========================================
# 🤵 AGENT & AGENCY CONFIGURATION
# ==========================================
AGENT_PROFILE = {
    "name": "Henry",
    "title": "Associate Division Director",
    "agency": "Huttons Asia Pte Ltd",
    "license": "L3008899K",
    "contact": "+65 9123 4567",
    "email": "henry@huttons.com"
}

CUSTOM_DISCLAIMER = """
**Disclaimer:**
This indicative valuation is generated by an Automated Valuation Model (AVM) based on historical transaction data and market trends. 
It is intended for general information purposes only and does not constitute a formal valuation report by a licensed appraiser. 
While every effort has been made to ensure accuracy, neither the agent nor Huttons Asia Pte Ltd accepts liability for any errors or omissions. 
The estimated profit is a gross figure and does not account for SSD, stamp duties, legal fees, or other transaction costs.
Past performance is not indicative of future results.
"""

# ==========================================
# 🛠️ DATA CLEANING & HELPER FUNCTIONS
# ==========================================

def clean_and_prepare_data(df_raw):
    df = df_raw.copy()
    rename_map = {
        'Transacted Price ($)': 'Sale Price',
        'Area (SQFT)': 'Area (sqft)',
        'Unit Price ($ psf)': 'Unit Price ($ psf)',
        'Unit Price ($ psm)': 'Unit Price ($ psm)',
        'Sale Date': 'Sale Date',
        'Bedroom Type': 'Type',   
        'No. of Bedroom': 'Type', 
        'Tenure': 'Tenure',
        'Lease Commencement Date': 'Tenure From',
        'Tenure Start Date': 'Tenure From',
        'Property Type': 'Sub Type',
        'Building Type': 'Sub Type'
    }
    df.rename(columns=rename_map, inplace=True)
    
    for col in ['Type', 'Tenure', 'Tenure From', 'Sub Type']:
        if col not in df.columns: df[col] = "N/A"
    
    df['Type'] = df['Type'].astype(str)
    if 'Sale Date' in df.columns: df['Sale Date'] = pd.to_datetime(df['Sale Date'], errors='coerce')
    
    if 'Unit Price ($ psf)' not in df.columns:
        if 'Sale Price' in df.columns and 'Area (sqft)' in df.columns:
            df['Unit Price ($ psf)'] = df['Sale Price'] / df['Area (sqft)']
        else:
            df['Unit Price ($ psf)'] = 0
            
    df['Floor_Int'] = pd.to_numeric(df['Floor'], errors='coerce').fillna(0).astype(int)
    return df

def format_unit(floor, stack):
    try:
        f_num = int(float(floor))
        s_str = str(stack)
        s_fmt = s_str.zfill(2) if s_str.isdigit() else s_str
        return f"#{f_num:02d}-{s_fmt}"
    except:
        return f"#{floor}-{stack}"

def format_unit_masked(floor):
    """用于隐私脱敏的格式化函数: #XX-XX"""
    try:
        f_num = int(float(floor))
        return f"#{f_num:02d}-XX"
    except:
        return f"#{floor}-XX"

def get_unit_specs(df, target_blk, target_floor, target_stack):
    this_unit = df[
        (df['BLK'] == target_blk) & 
        (df['Stack'] == target_stack) & 
        (df['Floor_Int'] == int(target_floor))
    ]
    
    if not this_unit.empty:
        rec = this_unit.sort_values('Sale Date', ascending=False).iloc[0]
        return rec['Area (sqft)'], rec['Type'], 'History', rec['Sale Price'], rec['Sale Date']
    
    same_stack = df[(df['BLK'] == target_blk) & (df['Stack'] == target_stack)]
    if not same_stack.empty:
        mode_area = same_stack['Area (sqft)'].mode()
        area = mode_area[0] if not mode_area.empty else same_stack['Area (sqft)'].mean()
        mode_type = same_stack['Type'].mode()
        u_type = mode_type[0] if not mode_type.empty else "N/A"
        return area, u_type, 'Stack Inference', 0, None
    
    default_area = df['Area (sqft)'].median() if not df.empty else 1000
    default_type = df['Type'].mode()[0] if not df.empty else "3 Bedroom"
    return default_area, default_type, 'Global Default', 0, None

def calculate_market_trend(full_df):
    limit_date = datetime.now() - pd.DateOffset(months=36)
    trend_data = full_df[full_df['Sale Date'] >= limit_date].copy()
    if len(trend_data) < 10: return 0.0
    
    trend_data['Date_Ord'] = trend_data['Sale Date'].map(datetime.toordinal)
    x = trend_data['Date_Ord']
    y = trend_data['Unit Price ($ psf)']
    
    try:
        slope, intercept = np.polyfit(x, y, 1)
        avg_price = y.mean()
        if avg_price == 0: return 0.0
        return max(-0.05, min(0.10, (slope / avg_price) * 365))
    except:
        return 0.0

def calculate_dynamic_floor_rate(comps):
    default_rate = 0.005 
    valid_data = comps[['Floor_Int', 'Unit Price ($ psf)']].dropna()
    if len(valid_data) < 3 or valid_data['Floor_Int'].nunique() < 2: return default_rate
    
    x = valid_data['Floor_Int']
    y = valid_data['Unit Price ($ psf)']
    try:
        slope, intercept = np.polyfit(x, y, 1)
        avg_psf = y.mean()
        if avg_psf == 0: return default_rate
        return max(-0.002, min(0.015, slope / avg_psf))
    except:
        return default_rate

# ==========================================
# 📄 PDF GENERATION (LETTER FORMAT)
# ==========================================

def generate_pdf_letter(project_name, blk, floor, stack, area, u_type, est_price, est_psf, comps_df, mailing_address, last_price=0, last_date=None):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=A4,
        rightMargin=72, leftMargin=72,
        topMargin=72, bottomMargin=72
    )
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='RightAlign', alignment=TA_RIGHT))
    styles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY, leading=14))
    styles.add(ParagraphStyle(name='Signature', fontSize=10, leading=12))
    
    elements = []
    
    # 1. Header (Agent Info)
    header_text = f"""
    <b>{AGENT_PROFILE['agency']}</b><br/>
    {AGENT_PROFILE['name']} | {AGENT_PROFILE['title']}<br/>
    {AGENT_PROFILE['contact']} | {AGENT_PROFILE['email']}<br/>
    CEA Reg: {AGENT_PROFILE['license']}
    """
    elements.append(Paragraph(header_text, styles['RightAlign']))
    elements.append(Spacer(1, 40))
    
    # 2. Date & Mailing Address (User Editable)
    date_str = datetime.now().strftime("%d %B %Y")
    
    # Convert newlines in address to <br/>
    address_formatted = mailing_address.replace("\n", "<br/>")
    
    address_text = f"""
    {date_str}<br/><br/>
    <b>To The Homeowner</b><br/>
    {address_formatted}
    """
    elements.append(Paragraph(address_text, styles['Normal']))
    elements.append(Spacer(1, 20))
    
    # 3. Salutation
    elements.append(Paragraph("<b>Dear Homeowner,</b>", styles['Normal']))
    elements.append(Spacer(1, 12))
    
    unit_display = format_unit(floor, stack)
    opening_text = f"""
    I hope this letter finds you well. As a resident specialist in {project_name}, 
    I have recently conducted a comprehensive valuation analysis for your unit at 
    <b>BLK {blk} {unit_display}</b> ({int(area):,} sqft, {u_type}).
    """
    elements.append(Paragraph(opening_text, styles['Justify']))
    elements.append(Spacer(1, 12))
    
    # 4. Valuation Result (Revised Structure)
    est_price_m = est_price / 1e6
    low_m = est_price_m * 0.9
    high_m = est_price_m * 1.1
    low_psf = est_psf * 0.9
    high_psf = est_psf * 1.1
    
    val_text = f"""
    Based on the latest transaction data and adjusting for your specific floor level and unit attributes, 
    the estimated market value of your property is:
    """
    elements.append(Paragraph(val_text, styles['Justify']))
    elements.append(Spacer(1, 10))
    
    # Highlight Styles
    highlight_style_main = ParagraphStyle(
        'HighlightMain', parent=styles['Normal'], 
        alignment=TA_CENTER, fontSize=16, textColor=colors.darkblue, spaceAfter=6
    )
    highlight_style_sub = ParagraphStyle(
        'HighlightSub', parent=styles['Normal'], 
        alignment=TA_CENTER, fontSize=10, textColor=colors.grey, spaceAfter=20
    )
    
    # Line 1: Exact Value
    elements.append(Paragraph(f"<b>${est_price_m:.2f} Million (${est_psf:,.0f} psf)</b>", highlight_style_main))
    # Line 2: Range
    range_txt = f"Valuation Range: ${low_m:.2f}M - ${high_m:.2f}M (${low_psf:,.0f} - ${high_psf:,.0f} psf)"
    elements.append(Paragraph(range_txt, highlight_style_sub))
    
    # 5. Profit Analysis
    if last_price > 0 and last_date is not None:
        profit = est_price - last_price
        profit_pct = (profit / last_price) * 100
        years_held = (datetime.now() - last_date).days / 365.0
        
        profit_text = f"""
        Records indicate this unit was last purchased on <b>{last_date.strftime('%Y-%m-%d')}</b> 
        for <b>${last_price/1e6:.2f}M</b>. Based on our current valuation, your estimated gross capital appreciation is:
        <br/><br/>
        <b><font color='green' size='12'>+${profit/1e6:.2f} Million ({profit_pct:.1f}%)</font></b>
        <br/><br/>
        This represents a significant return over the past {years_held:.1f} years.
        """
        elements.append(Paragraph(profit_text, styles['Justify']))
        elements.append(Spacer(1, 12))
    
    # 6. Supporting Data (Comparables - MASKED)
    elements.append(Paragraph("<b>Recent Comparable Transactions Used:</b>", styles['Normal']))
    elements.append(Spacer(1, 6))
    
    data = [['Date', 'Unit', 'Area', 'Price', 'PSF']]
    display_comps = comps_df.sort_values('Weight', ascending=False).head(5)
    
    for _, row in display_comps.iterrows():
        # Mask Stack Number
        c_unit_masked = f"BLK {row['BLK']} {format_unit_masked(row['Floor'])}"
        
        c_date = row['Sale Date'].strftime('%Y-%m-%d')
        c_price = f"${row['Sale Price']/1e6:.2f}M"
        c_psf = f"${row['Unit Price ($ psf)']:,.0f}"
        
        data.append([c_date, c_unit_masked, f"{int(row['Area (sqft)']):,}", c_price, c_psf])
        
    t = Table(data, colWidths=[1.2*inch, 1.5*inch, 0.8*inch, 1.0*inch, 0.8*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.Color(0.2, 0.2, 0.6)),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTSIZE', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))
    
    # 7. Closing
    closing_text = f"""
    The property market in {project_name} is dynamic. If you are considering restructuring your 
    property portfolio or simply wish to cash out on these profits, I would be happy to share 
    a more detailed marketing plan with you.
    <br/><br/>
    Please feel free to contact me at <b>{AGENT_PROFILE['contact']}</b>.
    """
    elements.append(Paragraph(closing_text, styles['Justify']))
    elements.append(Spacer(1, 30))
    
    # 8. Sign-off
    sign_text = f"""
    Sincerely,<br/><br/>
    <b>{AGENT_PROFILE['name']}</b><br/>
    {AGENT_PROFILE['title']}<br/>
    {AGENT_PROFILE['agency']}
    """
    elements.append(Paragraph(sign_text, styles['Signature']))
    elements.append(Spacer(1, 40))
    
    # 9. Disclaimer
    disclaimer_clean = CUSTOM_DISCLAIMER.replace("**", "").replace("\n", "<br/>")
    elements.append(Paragraph(f"<font size='7' color='grey'>{disclaimer_clean}</font>", styles['Justify']))
    
    doc.build(elements)
    buffer.seek(0)
    return buffer

# ==========================================
# 🧠 CORE LOGIC (AVM Calculation)
# ==========================================

def calculate_avm(df, target_blk, target_floor, target_stack, override_area=None, override_type=None):
    market_annual_growth = calculate_market_trend(df)

    # 1. Determine Specs
    last_tx_price = 0
    last_tx_date = None
    
    if override_area is not None and override_type is not None:
        est_area = override_area
        target_type = override_type
        # Try to find historical buy price
        _, _, _, hist_price, hist_date = get_unit_specs(df, target_blk, target_floor, target_stack)
        if hist_price > 0: 
            last_tx_price = hist_price
            last_tx_date = hist_date
            
        base_info_source = df[df['BLK'] == target_blk]
        if base_info_source.empty: base_info_source = df
        info_tenure = base_info_source['Tenure'].mode()[0] if not base_info_source['Tenure'].empty else '-'
        info_from = base_info_source['Tenure From'].mode()[0] if not base_info_source['Tenure From'].empty else '-'
        info_subtype = base_info_source['Sub Type'].mode()[0] if not base_info_source['Sub Type'].empty else '-'
    else:
        est_area, target_type, _, last_tx_price, last_tx_date = get_unit_specs(df, target_blk, target_floor, target_stack)
        
        rec_matches = df[(df['BLK']==target_blk) & (df['Stack']==target_stack)]
        if not rec_matches.empty:
            rec = rec_matches.iloc[0]
            info_tenure = str(rec.get('Tenure', '-'))
            info_from = str(rec.get('Tenure From', '-'))
            info_subtype = str(rec.get('Sub Type', '-'))
        else:
            info_tenure, info_from, info_subtype = '-', '-', '-'

    # 2. Filter Comps
    required_comps = 5
    thresholds = [0.05, 0.10, 0.15, 0.20]
    comps = pd.DataFrame()
    used_threshold = 0.0

    for t in thresholds:
        min_area = est_area * (1 - t)
        max_area = est_area * (1 + t)
        current_comps = df[(df['Area (sqft)'] >= min_area) & (df['Area (sqft)'] <= max_area)].copy()
        if len(current_comps) >= required_comps:
            comps = current_comps
            used_threshold = t
            break
            
    if comps.empty and 'current_comps' in locals():
        comps = current_comps
        used_threshold = 0.20
    
    if len(comps) < 2 and target_type != "N/A":
        comps = df[df['Type'] == target_type].copy()
        used_threshold = 9.99 

    # 3. Time Filter
    limit_date = datetime.now() - pd.DateOffset(months=36)
    recent_comps = comps[comps['Sale Date'] >= limit_date].copy()
    
    if recent_comps.empty:
        limit_date = datetime.now() - pd.DateOffset(months=60)
        recent_comps = comps[comps['Sale Date'] >= limit_date].copy()

    if recent_comps.empty:
        return None, None, {}, pd.DataFrame(), 0, 0, 0, 0, 0, 0

    # 4. Calculate Adjustment
    floor_adj_rate = calculate_dynamic_floor_rate(recent_comps)
    recent_comps['Floor_Int'] = pd.to_numeric(recent_comps['Floor'], errors='coerce').fillna(1)
    
    def apply_adjustment(row):
        floor_multiplier = 1 + (target_floor - row['Floor_Int']) * floor_adj_rate
        years_ago = (datetime.now() - row['Sale Date']).days / 365.0
        time_multiplier = 1 + (market_annual_growth * years_ago)
        return row['Unit Price ($ psf)'] * floor_multiplier * time_multiplier

    recent_comps['Adj_PSF'] = recent_comps.apply(apply_adjustment, axis=1)
    recent_comps['Days_Diff'] = (datetime.now() - recent_comps['Sale Date']).dt.days
    recent_comps['Weight'] = 1 / (recent_comps['Days_Diff'] + 30)
    
    weighted_psf = (recent_comps['Adj_PSF'] * recent_comps['Weight']).sum() / recent_comps['Weight'].sum()
    est_psf = weighted_psf
    est_price = est_psf * est_area
    
    extra_info = {
        'tenure': info_tenure,
        'from': info_from,
        'subtype': info_subtype,
        'type': target_type,
        'last_price': last_tx_price,
        'last_date': last_tx_date
    }
    
    return est_price, est_psf, extra_info, recent_comps, est_area, floor_adj_rate, market_annual_growth, used_threshold

# --- 渲染仪表盘 ---
def render_gauge(est_psf, font_size=12):
    range_min = est_psf * 0.90
    range_max = est_psf * 1.10
    axis_min = est_psf * 0.80
    axis_max = est_psf * 1.20
        
    fig = go.Figure(go.Indicator(
        mode = "gauge+number",
        value = est_psf,
        number = {'suffix': " psf", 'font': {'size': 18}}, 
        domain = {'x': [0, 1], 'y': [0, 1]},
        gauge = {
            'axis': {
                'range': [axis_min, axis_max], 
                'tickwidth': 1, 
                'tickcolor': "darkblue",
                'tickmode': 'array',
                'tickvals': [axis_min, est_psf, axis_max],
                'ticktext': [f"{int(axis_min)}", f"{int(est_psf)}", f"{int(axis_max)}"]
            },
            'bar': {'thickness': 0}, 
            'bgcolor': "white",
            'borderwidth': 2,
            'bordercolor': "#e5e7eb",
            'steps': [
                {'range': [axis_min, range_min], 'color': "#f3f4f6"},
                {'range': [range_min, range_max], 'color': "#2563eb"},
                {'range': [range_max, axis_max], 'color': "#f3f4f6"}
            ],
            'threshold': {
                'line': {'color': "#dc2626", 'width': 3},
                'thickness': 0.8,
                'value': est_psf
            }
        }
    ))
    fig.update_layout(
        height=150, 
        margin=dict(l=20, r=20, t=10, b=10),
        paper_bgcolor="rgba(0,0,0,0)",
        font={'family': "Arial", 'size': 11}
    )
    return fig

# ==========================================
# 🖥️ MAIN RENDER FUNCTION
# ==========================================

def render(df_raw, project_name="Project", chart_font_size=12):
    st.subheader("🤖 智能估值 (AVM)")

    target = st.session_state.get('avm_target', None)
    if not target:
        st.info("👈 请先在 **楼宇透视 (Tab 2)** 点击任意单位，即可在此查看估值详情。")
        return

    blk, floor, stack = target['blk'], target['floor'], target['stack']
    df = clean_and_prepare_data(df_raw)
    
    # 1. Params & Calibration
    sys_area, sys_type, sys_source, _, _ = get_unit_specs(df, blk, floor, stack)
    all_types = sorted(df['Type'].unique().tolist())
    if sys_type not in all_types: all_types.insert(0, sys_type)
    
    widget_key_suffix = f"{blk}_{floor}_{stack}"
    with st.expander("⚙️ 调整参数 (Calibration)", expanded=True):
        c_cal1, c_cal2 = st.columns(2)
        with c_cal1:
            input_area = st.number_input(
                "面积 (sqft)", value=int(sys_area) if pd.notna(sys_area) else 0, step=10, key=f"cal_area_{widget_key_suffix}"
            )
        with c_cal2:
            input_type = st.selectbox(
                "户型 (Type)", options=all_types, index=all_types.index(sys_type) if sys_type in all_types else 0, key=f"cal_type_{widget_key_suffix}"
            )
    
    # 2. Calculate
    est_price, est_psf, extra_info, comps, area, floor_adj, market_growth, used_threshold = calculate_avm(
        df, blk, floor, stack, 
        override_area=input_area, 
        override_type=input_type
    )
    
    if est_price is None:
        st.error(f"⚠️ 数据严重不足，无法估值。")
        return

    # 3. Main Dashboard
    formatted_unit_str = format_unit(floor, stack)
    info_parts = [f"{int(area):,} sqft"]
    if extra_info['type'] != 'N/A': info_parts.append(str(extra_info['type'])) 
    if extra_info['tenure'] != '-' and extra_info['tenure'] != 'N/A': info_parts.append(str(extra_info['tenure']))
    info_str = " | ".join(info_parts)
    
    st.markdown(f"""
    <div style="background-color:#f8fafc; padding:15px; border-radius:8px; border:1px solid #e2e8f0; margin-bottom:20px;">
        <p style="margin:0 0 5px 0; color:#64748b; font-size:12px; font-weight:bold; letter-spacing:1px; text-transform:uppercase;">
            {project_name}
        </p>
        <h3 style="margin:0; color:#1e293b; font-size:24px;">BLK {blk} {formatted_unit_str}</h3>
        <p style="margin:5px 0 0 0; color:#475569; font-size:15px; font-weight:500;">
            {info_str}
        </p>
    </div>
    """, unsafe_allow_html=True)

    c1, c2 = st.columns([1, 1.5])
    low_bound = est_price * 0.90
    high_bound = est_price * 1.10
    
    with c1:
        st.metric(label="预估总价 (Est. Price)", value=f"${est_price/1e6:,.2f}M")
        
        last_price = extra_info.get('last_price', 0)
        if last_price > 0:
            profit = est_price - last_price
            profit_pct = (profit / last_price) * 100
            st.markdown(f"""
            <div style="margin-top:5px; margin-bottom:10px; font-size:14px; color:#15803d; font-weight:bold;">
                📈 预计增值: +${profit/1e6:.2f}M ({profit_pct:.1f}%)
            </div>
            """, unsafe_allow_html=True)
        
        st.markdown(f"""
        <div style="margin-top:10px; padding:10px; background:#2563eb; border-radius:4px; font-size:13px; color:white;">
            <strong>合理区间 (+/- 10%):</strong><br>${low_bound/1e6:.2f}M - ${high_bound/1e6:.2f}M
        </div>
        """, unsafe_allow_html=True)

    with c2:
        st.plotly_chart(render_gauge(est_psf, chart_font_size), use_container_width=True, key=f"gauge_{blk}_{floor}_{stack}_{time.time()}")

    st.divider()

    # 4. Comps Table
    st.markdown("#### 🏘️ 参考交易 (Comparable Transactions)")
    comps_display = comps.sort_values('Weight', ascending=False).head(5).copy()
    comps_display['Sale Date'] = comps_display['Sale Date'].dt.strftime('%Y-%m-%d')
    comps_display['Sale Price'] = comps_display['Sale Price'].apply(lambda x: f"${x/1e6:.2f}M")
    comps_display['Unit Price ($ psf)'] = comps_display['Unit Price ($ psf)'].apply(lambda x: f"${x:,.0f}")
    comps_display['Unit'] = comps_display.apply(lambda row: f"BLK {row['BLK']} {format_unit(row['Floor'], row['Stack'])}", axis=1)
    
    st.dataframe(comps_display[['Sale Date', 'Unit', 'Area (sqft)', 'Sale Price', 'Unit Price ($ psf)']], use_container_width=True, hide_index=True)

    st.divider()
    
    # 5. [V188 Feature] Address Verification & PDF Download
    st.markdown("### 📄 报告生成 (Report Generation)")
    
    # A. Address Input with Google Map Link
    default_address = f"Block {blk} Braddell Hill, {formatted_unit_str}\nBraddell View\nSingapore"
    
    col_addr, col_map = st.columns([3, 1])
    with col_addr:
        mailing_address = st.text_area(
            "📍 确认收件地址 (Mailing Address)", 
            value=default_address, 
            height=100,
            key=f"addr_{widget_key_suffix}"
        )
    with col_map:
        st.write("") # Spacer
        st.write("") 
        # Generate Google Map Query
        query_str = urllib.parse.quote(f"{project_name} Block {blk}")
        map_url = f"https://www.google.com/maps/search/?api=1&query={query_str}"
        st.link_button("🗺️ 在 Google Map 中核对", map_url)

    # B. Generate PDF with confirmed address
    pdf_bytes = generate_pdf_letter(
        project_name, blk, floor, stack, 
        area, extra_info['type'], 
        est_price, est_psf, comps,
        mailing_address=mailing_address, # Pass user edited address
        last_price=extra_info.get('last_price', 0),
        last_date=extra_info.get('last_date', None)
    )
    
    st.download_button(
        label="📥 下载致业主信函 (Download Letter to Owner)",
        data=pdf_bytes,
        file_name=f"Letter_{blk}_{formatted_unit_str}.pdf",
        mime="application/pdf",
        type="primary",
        use_container_width=True,
        key=f"dl_pdf_{blk}_{floor}_{stack}_{time.time()}"
    )
